/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Service health */
        get: operations["get_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Data Dragon version, region, queues */
        get: operations["get_meta"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search known summoners by game name (accepts 'Name#TAG'); tracked players first */
        get: operations["search_summoners"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/summoners/by-riot-id/{game_name}/{tag_line}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Profile by Riot ID (resolves unknown players through Riot) */
        get: operations["get_summoner_profile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/summoners/by-riot-id/{game_name}/{tag_line}/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Update button: refresh rank and ingest new matches (rate limited per player) */
        post: operations["refresh_summoner"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/summoners/{puuid}/matches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Match history, newest first (cursor paginated) */
        get: operations["list_summoner_matches"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/summoners/{puuid}/ranks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Rank snapshots for one queue, oldest first */
        get: operations["get_rank_history"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/summoners/{puuid}/ai-trend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stored AI scores over recent games (works without a loaded model) */
        get: operations["get_ai_trend"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/summoners/{puuid}/ai-explain": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Which stats drive this player's AI Score (gradient x input) */
        get: operations["get_ai_explain"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/summoners/{puuid}/insights/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Tilt detector: win rate and AI Score by game number within a play session */
        get: operations["get_session_insights"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/summoners/{puuid}/insights/schedule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Best time to play: win rate by day of week and hour (in the given time zone) */
        get: operations["get_schedule_insights"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/summoners/{puuid}/insights/matchups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Nemesis champions: record against each enemy champion in the player's lane */
        get: operations["get_matchup_insights"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/summoners/{puuid}/insights/luck": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Unlucky losses (high score, lost) and lucky wins (low score, won) */
        get: operations["get_luck_insights"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/matches/{match_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Both teams, objectives, bans and AI scores for one stored match */
        get: operations["get_match"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/leaderboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Season leaderboard of the tracked roster */
        get: operations["get_leaderboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/roster": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Tracked players */
        get: operations["list_roster"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/roster/{game_name}/{tag_line}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Start tracking a player (admin) */
        put: operations["add_roster_entry"];
        post?: never;
        /** Stop tracking a player (admin); match data is kept */
        delete: operations["remove_roster_entry"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/squad/pairs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Duo synergy and who carries whom for every pair of tracked players */
        get: operations["get_squad_pairs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/squad/stacks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stacks (games the squad played together): record, awards, lineups, highlights */
        get: operations["get_stack_summary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/squad/stacks/games": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stacked games, newest first (cursor paginated) */
        get: operations["get_stack_games"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/squad/recent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The roster's most recent games, newest first (cursor paginated)
         * @description Every game a roster player played (the same rows as the Stacks page with a minimum of
         *     one roster player): all queues except Arena and customs, remakes excluded. Friends on the
         *     same team share a row, with the stack verdict when there are two or more.
         */
        get: operations["get_recent_games"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Games roster players are in right now (as of the worker's last check) */
        get: operations["get_live_games"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/records": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Single-game records (roster, or one player with ?puuid=) and pentakills */
        get: operations["get_records"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AiExplain */
        AiExplain: {
            /** Puuid */
            puuid: string;
            /** Model Version */
            model_version: string;
            /** N Matches */
            n_matches: number;
            /** Base Score */
            base_score: number | null;
            /** Features */
            features: components["schemas"]["FeatureAttribution"][];
        };
        /** AiTrend */
        AiTrend: {
            /** Puuid */
            puuid: string;
            /** Model Version */
            model_version: string | null;
            /** Average */
            average: number | null;
            /** Points */
            points: components["schemas"]["AiTrendPoint"][];
        };
        /** AiTrendPoint */
        AiTrendPoint: {
            /** Match Id */
            match_id: string;
            /**
             * Game Start
             * Format: date-time
             */
            game_start: string;
            /** Champion Name */
            champion_name: string;
            /** Win */
            win: boolean;
            /** Ai Score */
            ai_score: number;
        };
        /** BestAlly */
        BestAlly: {
            /** Puuid */
            puuid: string;
            /** Game Name */
            game_name: string;
            /** Tag Line */
            tag_line: string;
            /** Games */
            games: number;
            /** Wins */
            wins: number;
            /** Winrate */
            winrate: number;
        };
        /**
         * ChampionMatchup
         * @description The player's record against one enemy champion in their lane.
         */
        ChampionMatchup: {
            /** Champion Id */
            champion_id: number;
            /** Champion Name */
            champion_name: string;
            /** Games */
            games: number;
            /** Wins */
            wins: number;
            /** Losses */
            losses: number;
            /** Winrate */
            winrate: number;
            /** Avg Ai Score */
            avg_ai_score: number | null;
            /** Avg Gold Diff */
            avg_gold_diff: number;
        };
        /** ChampionStat */
        ChampionStat: {
            /** Champion Id */
            champion_id: number;
            /** Champion Name */
            champion_name: string;
            /** Games */
            games: number;
            /** Wins */
            wins: number;
            /** Winrate */
            winrate: number;
            /** Kda */
            kda: number;
            /** Avg Ai Score */
            avg_ai_score: number | null;
        };
        /** ErrorResponse */
        ErrorResponse: {
            /** Detail */
            detail: string;
            /** Code */
            code: string | null;
        };
        /** FeatureAttribution */
        FeatureAttribution: {
            /** Feature */
            feature: string;
            /** Label */
            label: string;
            /**
             * Group
             * @enum {string}
             */
            group: "combat" | "economy" | "vision" | "objectives" | "survival" | "teamplay";
            /** Mean Attribution */
            mean_attribution: number;
            /** Mean Abs Attribution */
            mean_abs_attribution: number;
            /** Player Value */
            player_value: number;
            /** Population Value */
            population_value: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
            /** Version */
            version: string;
            /** Db Ok */
            db_ok: boolean;
            model: components["schemas"]["HealthModel"];
            riot: components["schemas"]["HealthRiot"];
            poller: components["schemas"]["HealthPoller"];
            bot: components["schemas"]["HealthBot"];
        };
        /** HealthBot */
        HealthBot: {
            /** Configured */
            configured: boolean;
            /** Running */
            running: boolean;
            /** Connected */
            connected: boolean;
            /** Heartbeat At */
            heartbeat_at: string | null;
            /** Last Error */
            last_error: string | null;
        };
        /** HealthModel */
        HealthModel: {
            /** Loaded */
            loaded: boolean;
            /** Version */
            version: string | null;
            /** Trained At */
            trained_at: string | null;
            /** N Features */
            n_features: number | null;
        };
        /** HealthPoller */
        HealthPoller: {
            /** Last Run At */
            last_run_at: string | null;
            /** Last Error */
            last_error: string | null;
            /** Running */
            running: boolean;
        };
        /** HealthRiot */
        HealthRiot: {
            /** Key Configured */
            key_configured: boolean;
            /** Key Ok */
            key_ok: boolean | null;
            /** Last Error */
            last_error: string | null;
        };
        /** Leaderboard */
        Leaderboard: {
            /**
             * Season Start
             * Format: date-time
             */
            season_start: string;
            /** Model Version */
            model_version: string | null;
            /**
             * Queue
             * @enum {string}
             */
            queue: "all" | "solo" | "flex";
            /** Entries */
            entries: components["schemas"]["LeaderboardEntry"][];
        };
        /** LeaderboardEntry */
        LeaderboardEntry: {
            /** Puuid */
            puuid: string;
            /** Game Name */
            game_name: string;
            /** Tag Line */
            tag_line: string;
            /** Profile Icon Id */
            profile_icon_id: number | null;
            /** Summoner Level */
            summoner_level: number | null;
            solo: components["schemas"]["RankEntry"] | null;
            flex: components["schemas"]["RankEntry"] | null;
            /** Games */
            games: number;
            /** Wins */
            wins: number;
            /** Losses */
            losses: number;
            /** Winrate */
            winrate: number;
            /** Kda */
            kda: number;
            /** Avg Kills */
            avg_kills: number;
            /** Avg Deaths */
            avg_deaths: number;
            /** Avg Assists */
            avg_assists: number;
            /** Avg Ai Score */
            avg_ai_score: number | null;
            /** Avg Ai Role Percentile */
            avg_ai_role_percentile: number | null;
            /** Lp Delta */
            lp_delta: number | null;
            best_ally: components["schemas"]["BestAlly"] | null;
            /** Top Champions */
            top_champions: string[];
            /** Recent Form */
            recent_form: boolean[];
        };
        /** LiveBan */
        LiveBan: {
            /** Champion Id */
            champion_id: number;
            /** Champion Name */
            champion_name: string | null;
            /**
             * Team Id
             * @enum {integer}
             */
            team_id: 100 | 200;
        };
        /** LiveGame */
        LiveGame: {
            /** Game Id */
            game_id: number;
            /** Match Id */
            match_id: string;
            /** Platform */
            platform: string;
            /** Queue Id */
            queue_id: number | null;
            /** Queue Label */
            queue_label: string;
            /** Game Mode */
            game_mode: string | null;
            /** Map Id */
            map_id: number | null;
            /** Started At */
            started_at: string | null;
            /**
             * First Seen At
             * Format: date-time
             */
            first_seen_at: string;
            /**
             * Seen At
             * Format: date-time
             */
            seen_at: string;
            /** Bans */
            bans: components["schemas"]["LiveBan"][];
            /** Participants */
            participants: components["schemas"]["LiveParticipant"][];
        };
        /**
         * LiveGames
         * @description Games roster players are in right now, as of the worker's last check.
         */
        LiveGames: {
            /** Checked At */
            checked_at: string | null;
            /** Interval Seconds */
            interval_seconds: number;
            /** Games */
            games: components["schemas"]["LiveGame"][];
        };
        /**
         * LiveParticipant
         * @description One of the ten players in a live game, with what HexTrack knows about them.
         */
        LiveParticipant: {
            /** Puuid */
            puuid: string | null;
            /** Game Name */
            game_name: string | null;
            /** Tag Line */
            tag_line: string | null;
            /**
             * Team Id
             * @enum {integer}
             */
            team_id: 100 | 200;
            /** Champion Id */
            champion_id: number;
            /** Champion Name */
            champion_name: string | null;
            /** Spell1 Id */
            spell1_id: number;
            /** Spell2 Id */
            spell2_id: number;
            /** Keystone Id */
            keystone_id: number | null;
            /** Primary Style Id */
            primary_style_id: number | null;
            /** Secondary Style Id */
            secondary_style_id: number | null;
            /** Profile Icon Id */
            profile_icon_id: number | null;
            /** Bot */
            bot: boolean;
            /** Is Tracked */
            is_tracked: boolean;
            solo: components["schemas"]["RankEntry"] | null;
            flex: components["schemas"]["RankEntry"] | null;
            /** Season Games */
            season_games: number;
            /** Season Wins */
            season_wins: number;
            /** Avg Ai Score */
            avg_ai_score: number | null;
            /** Champion Games */
            champion_games: number;
            /** Champion Wins */
            champion_wins: number;
        };
        /** LuckGame */
        LuckGame: {
            /** Match Id */
            match_id: string;
            /**
             * Game Start
             * Format: date-time
             */
            game_start: string;
            /** Queue Id */
            queue_id: number;
            /** Champion Name */
            champion_name: string;
            /**
             * Team Position
             * @enum {string}
             */
            team_position: "TOP" | "JUNGLE" | "MIDDLE" | "BOTTOM" | "UTILITY" | "UNKNOWN";
            /** Kills */
            kills: number;
            /** Deaths */
            deaths: number;
            /** Assists */
            assists: number;
            /** Duration */
            duration: number;
            /** Ai Score */
            ai_score: number;
            /** Ai Role Percentile */
            ai_role_percentile: number | null;
        };
        /**
         * LuckInsights
         * @description Unlucky losses (lost, but scored >= high_threshold) and lucky wins (won, but scored
         *     <= low_threshold), from games scored by the active model.
         */
        LuckInsights: {
            /** Puuid */
            puuid: string;
            /**
             * Since
             * @enum {string}
             */
            since: "season" | "all";
            /**
             * Queue
             * @enum {string}
             */
            queue: "all" | "solo" | "flex";
            /** Model Version */
            model_version: string | null;
            /** High Threshold */
            high_threshold: number;
            /** Low Threshold */
            low_threshold: number;
            /** Losses Scored */
            losses_scored: number;
            /** Unlucky Count */
            unlucky_count: number;
            /** Wins Scored */
            wins_scored: number;
            /** Lucky Count */
            lucky_count: number;
            /** Unlucky Losses */
            unlucky_losses: components["schemas"]["LuckGame"][];
            /** Lucky Wins */
            lucky_wins: components["schemas"]["LuckGame"][];
        };
        /** MatchDetail */
        MatchDetail: {
            /** Match Id */
            match_id: string;
            /** Queue Id */
            queue_id: number;
            /** Queue Label */
            queue_label: string;
            /** Game Mode */
            game_mode: string;
            /** Game Version */
            game_version: string;
            /** Patch */
            patch: string;
            /**
             * Game Start
             * Format: date-time
             */
            game_start: string;
            /** Game Duration */
            game_duration: number;
            /** Remake */
            remake: boolean;
            /** Model Version */
            model_version: string | null;
            /** Teams */
            teams: components["schemas"]["TeamDetail"][];
        };
        /** MatchPage */
        MatchPage: {
            /** Items */
            items: components["schemas"]["MatchSummary"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** MatchSummary */
        MatchSummary: {
            /** Match Id */
            match_id: string;
            /** Queue Id */
            queue_id: number;
            /** Queue Label */
            queue_label: string;
            /** Game Mode */
            game_mode: string;
            /**
             * Game Start
             * Format: date-time
             */
            game_start: string;
            /** Game Duration */
            game_duration: number;
            /** Patch */
            patch: string;
            /** Remake */
            remake: boolean;
            me: components["schemas"]["ParticipantSummary"];
            /** Teams */
            teams: components["schemas"]["TeamSummary"][];
        };
        /**
         * MatchupInsights
         * @description Nemesis champions. The lane opponent is the enemy with the same ``team_position``;
         *     games where the position is UNKNOWN / empty or not exactly one per team are skipped.
         */
        MatchupInsights: {
            /** Puuid */
            puuid: string;
            /**
             * Since
             * @enum {string}
             */
            since: "season" | "all";
            /**
             * Queue
             * @enum {string}
             */
            queue: "all" | "solo" | "flex";
            /** Model Version */
            model_version: string | null;
            /** Min Games */
            min_games: number;
            /** Total Matchups */
            total_matchups: number;
            /** Nemeses */
            nemeses: components["schemas"]["ChampionMatchup"][];
            /** Favorites */
            favorites: components["schemas"]["ChampionMatchup"][];
        };
        /** Meta */
        Meta: {
            /** Ddragon Version */
            ddragon_version: string;
            /** Ddragon Cdn */
            ddragon_cdn: string;
            /** Platform */
            platform: string;
            /** Region */
            region: string;
            /**
             * Season Start
             * Format: date-time
             */
            season_start: string;
            /** Model Version */
            model_version: string | null;
            /** Model Trained At */
            model_trained_at: string | null;
            /** Queues */
            queues: {
                [key: string]: string;
            };
        };
        /** ObjectiveStat */
        ObjectiveStat: {
            /** First */
            first: boolean;
            /** Kills */
            kills: number;
        };
        /** ParticipantSummary */
        ParticipantSummary: {
            /** Puuid */
            puuid: string;
            /** Game Name */
            game_name: string | null;
            /** Tag Line */
            tag_line: string | null;
            /** Participant Id */
            participant_id: number;
            /**
             * Team Id
             * @enum {integer}
             */
            team_id: 100 | 200;
            /** Subteam Id */
            subteam_id: number | null;
            /** Placement */
            placement: number | null;
            /**
             * Team Position
             * @enum {string}
             */
            team_position: "TOP" | "JUNGLE" | "MIDDLE" | "BOTTOM" | "UTILITY" | "UNKNOWN";
            /** Champion Id */
            champion_id: number;
            /** Champion Name */
            champion_name: string;
            /** Champ Level */
            champ_level: number;
            /** Win */
            win: boolean;
            /** Kills */
            kills: number;
            /** Deaths */
            deaths: number;
            /** Assists */
            assists: number;
            /** Kda */
            kda: number;
            /** Kill Participation */
            kill_participation: number;
            /** Cs */
            cs: number;
            /** Cs Per Min */
            cs_per_min: number;
            /** Gold */
            gold: number;
            /** Gold Per Min */
            gold_per_min: number;
            /** Damage To Champions */
            damage_to_champions: number;
            /** Damage Per Min */
            damage_per_min: number;
            /** Damage Taken */
            damage_taken: number;
            /** Vision Score */
            vision_score: number;
            /** Wards Placed */
            wards_placed: number;
            /** Wards Killed */
            wards_killed: number;
            /** Control Wards */
            control_wards: number;
            /** Items */
            items: number[];
            /** Summoner1 Id */
            summoner1_id: number;
            /** Summoner2 Id */
            summoner2_id: number;
            /** Largest Multikill */
            largest_multikill: number;
            /** Ai Score */
            ai_score: number | null;
            /** Ai Rank */
            ai_rank: number | null;
            /** Is Tracked */
            is_tracked: boolean;
            /** Ai Role Percentile */
            ai_role_percentile: number | null;
        };
        /**
         * ProfileStats
         * @description Season aggregates over ranked queues (420, 440), remakes excluded.
         */
        ProfileStats: {
            /** Games */
            games: number;
            /** Wins */
            wins: number;
            /** Losses */
            losses: number;
            /** Winrate */
            winrate: number;
            /** Avg Kills */
            avg_kills: number;
            /** Avg Deaths */
            avg_deaths: number;
            /** Avg Assists */
            avg_assists: number;
            /** Kda */
            kda: number;
            /** Avg Cs Per Min */
            avg_cs_per_min: number;
            /** Avg Damage Per Min */
            avg_damage_per_min: number;
            /** Avg Vision Per Min */
            avg_vision_per_min: number;
            /** Avg Kill Participation */
            avg_kill_participation: number;
            /** Avg Ai Score */
            avg_ai_score: number | null;
            /** Ai Scored Games */
            ai_scored_games: number;
            /** Avg Ai Role Percentile */
            avg_ai_role_percentile: number | null;
        };
        /** QuadrakillCount */
        QuadrakillCount: {
            /** Puuid */
            puuid: string;
            /** Game Name */
            game_name: string;
            /** Tag Line */
            tag_line: string;
            /** Count */
            count: number;
        };
        /** RankEntry */
        RankEntry: {
            /**
             * Queue Type
             * @enum {string}
             */
            queue_type: "RANKED_SOLO_5x5" | "RANKED_FLEX_SR";
            /**
             * Tier
             * @enum {string}
             */
            tier: "IRON" | "BRONZE" | "SILVER" | "GOLD" | "PLATINUM" | "EMERALD" | "DIAMOND" | "MASTER" | "GRANDMASTER" | "CHALLENGER";
            /** Rank */
            rank: ("I" | "II" | "III" | "IV") | null;
            /** Lp */
            lp: number;
            /** Wins */
            wins: number;
            /** Losses */
            losses: number;
            /** Winrate */
            winrate: number;
            /** Rank Value */
            rank_value: number;
            /**
             * Taken At
             * Format: date-time
             */
            taken_at: string;
        };
        /** RankHistory */
        RankHistory: {
            /** Puuid */
            puuid: string;
            /**
             * Queue Type
             * @enum {string}
             */
            queue_type: "RANKED_SOLO_5x5" | "RANKED_FLEX_SR";
            /** Points */
            points: components["schemas"]["RankPoint"][];
        };
        /** RankPoint */
        RankPoint: {
            /**
             * Taken At
             * Format: date-time
             */
            taken_at: string;
            /**
             * Tier
             * @enum {string}
             */
            tier: "IRON" | "BRONZE" | "SILVER" | "GOLD" | "PLATINUM" | "EMERALD" | "DIAMOND" | "MASTER" | "GRANDMASTER" | "CHALLENGER";
            /** Rank */
            rank: ("I" | "II" | "III" | "IV") | null;
            /** Lp */
            lp: number;
            /** Rank Value */
            rank_value: number;
            /** Wins */
            wins: number;
            /** Losses */
            losses: number;
        };
        /** RecordCategory */
        RecordCategory: {
            /**
             * Key
             * @enum {string}
             */
            key: "most_kills" | "most_assists" | "most_deaths" | "best_kda" | "most_damage" | "highest_damage_per_min" | "most_cs" | "highest_cs_per_min" | "most_gold" | "highest_vision" | "highest_kill_participation" | "longest_game" | "fastest_win" | "highest_ai_score" | "largest_killing_spree" | "most_damage_taken" | "most_healing";
            /** Label */
            label: string;
            /**
             * Unit
             * @enum {string}
             */
            unit: "count" | "number" | "percent" | "duration" | "per_min" | "score";
            /** Higher Is Better */
            higher_is_better: boolean;
            /** Entries */
            entries: components["schemas"]["RecordEntry"][];
        };
        /**
         * RecordEntry
         * @description One game holding a record (or a pentakill game).
         */
        RecordEntry: {
            /** Rank */
            rank: number;
            /** Value */
            value: number;
            /** Puuid */
            puuid: string;
            /** Game Name */
            game_name: string;
            /** Tag Line */
            tag_line: string;
            /** Champion Name */
            champion_name: string;
            /** Match Id */
            match_id: string;
            /**
             * Game Start
             * Format: date-time
             */
            game_start: string;
            /** Win */
            win: boolean;
        };
        /**
         * Records
         * @description Single-game records. Scope "roster" = all tracked players; "player" = only ``puuid``
         *     (tracked or not). best_kda needs at least 5 takedowns; highest_kill_participation needs
         *     at least 10 team kills; highest_ai_score only uses active-model scores. A record must be
         *     above zero. longest_game and fastest_win list each match once (the friend with the
         *     lowest participant id).
         */
        Records: {
            /**
             * Since
             * @enum {string}
             */
            since: "season" | "all";
            /**
             * Queue
             * @enum {string}
             */
            queue: "all" | "solo" | "flex";
            /**
             * Scope
             * @enum {string}
             */
            scope: "roster" | "player";
            /** Puuid */
            puuid: string | null;
            /** Model Version */
            model_version: string | null;
            /** Limit */
            limit: number;
            /** Categories */
            categories: components["schemas"]["RecordCategory"][];
            /** Pentakills */
            pentakills: components["schemas"]["RecordEntry"][];
            /** Quadrakills */
            quadrakills: components["schemas"]["QuadrakillCount"][];
        };
        /** RefreshResult */
        RefreshResult: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "cooldown" | "partial" | "unavailable";
            /** New Matches */
            new_matches: number;
            /** Pending */
            pending: number;
            /**
             * Next Allowed At
             * Format: date-time
             */
            next_allowed_at: string;
            /** Message */
            message: string;
            profile: components["schemas"]["SummonerProfile"];
        };
        /** RoleStat */
        RoleStat: {
            /**
             * Position
             * @enum {string}
             */
            position: "TOP" | "JUNGLE" | "MIDDLE" | "BOTTOM" | "UTILITY" | "UNKNOWN";
            /** Games */
            games: number;
            /** Wins */
            wins: number;
            /** Winrate */
            winrate: number;
        };
        /** RosterEntry */
        RosterEntry: {
            /** Puuid */
            puuid: string;
            /** Game Name */
            game_name: string;
            /** Tag Line */
            tag_line: string;
            /** Tracked Since */
            tracked_since: string | null;
            /** Profile Icon Id */
            profile_icon_id: number | null;
        };
        /** ScheduleCell */
        ScheduleCell: {
            /** Dow */
            dow: number;
            /** Hour */
            hour: number;
            /** Games */
            games: number;
            /** Wins */
            wins: number;
            /** Avg Ai Score */
            avg_ai_score: number | null;
        };
        /** ScheduleDay */
        ScheduleDay: {
            /** Dow */
            dow: number;
            /** Games */
            games: number;
            /** Wins */
            wins: number;
            /** Winrate */
            winrate: number;
            /** Avg Ai Score */
            avg_ai_score: number | null;
        };
        /** ScheduleHour */
        ScheduleHour: {
            /** Hour */
            hour: number;
            /** Games */
            games: number;
            /** Wins */
            wins: number;
            /** Winrate */
            winrate: number;
            /** Avg Ai Score */
            avg_ai_score: number | null;
        };
        /**
         * ScheduleInsights
         * @description Best time to play: win rate by local day of week and hour of game start.
         */
        ScheduleInsights: {
            /** Puuid */
            puuid: string;
            /**
             * Since
             * @enum {string}
             */
            since: "season" | "all";
            /**
             * Queue
             * @enum {string}
             */
            queue: "all" | "solo" | "flex";
            /** Model Version */
            model_version: string | null;
            /** Tz */
            tz: string;
            /** Min Games */
            min_games: number;
            /** Cells */
            cells: components["schemas"]["ScheduleCell"][];
            /** By Dow */
            by_dow: components["schemas"]["ScheduleDay"][];
            /** By Hour */
            by_hour: components["schemas"]["ScheduleHour"][];
            best_window: components["schemas"]["ScheduleWindow"] | null;
            worst_window: components["schemas"]["ScheduleWindow"] | null;
        };
        /**
         * ScheduleWindow
         * @description Three consecutive hours on one day of week (never crossing midnight).
         */
        ScheduleWindow: {
            /** Dow */
            dow: number;
            /** Start Hour */
            start_hour: number;
            /** End Hour */
            end_hour: number;
            /** Games */
            games: number;
            /** Winrate */
            winrate: number;
        };
        /** SessionGameBucket */
        SessionGameBucket: {
            /** N */
            n: number;
            /** Games */
            games: number;
            /** Wins */
            wins: number;
            /** Winrate */
            winrate: number;
            /** Avg Ai Score */
            avg_ai_score: number | null;
        };
        /**
         * SessionInsights
         * @description Tilt detector. A session = consecutive ranked games of the player where
         *     ``next.game_start - (previous.game_start + previous.duration) <= gap_minutes``.
         */
        SessionInsights: {
            /** Puuid */
            puuid: string;
            /**
             * Since
             * @enum {string}
             */
            since: "season" | "all";
            /**
             * Queue
             * @enum {string}
             */
            queue: "all" | "solo" | "flex";
            /** Model Version */
            model_version: string | null;
            /** Gap Minutes */
            gap_minutes: number;
            /** Min Games */
            min_games: number;
            /** Sessions */
            sessions: number;
            /** Games */
            games: number;
            /** Avg Session Games */
            avg_session_games: number;
            /** Longest Session Games */
            longest_session_games: number;
            /** By Game Number */
            by_game_number: components["schemas"]["SessionGameBucket"][];
            /** By State */
            by_state: components["schemas"]["SessionStateBucket"][];
        };
        /** SessionStateBucket */
        SessionStateBucket: {
            /**
             * State
             * @enum {string}
             */
            state: "first_game" | "after_win" | "after_one_loss" | "after_two_plus_losses";
            /** Games */
            games: number;
            /** Wins */
            wins: number;
            /** Winrate */
            winrate: number;
            /** Avg Ai Score */
            avg_ai_score: number | null;
        };
        /**
         * SquadPair
         * @description Two roster players who played ranked games on the SAME team.
         *
         *     Duo synergy: ``games``/``wins``/``winrate`` of their shared games, compared with
         *     ``expected_winrate``. Who carries whom: over ``scored_games`` (shared games where both
         *     have an active-model score), how often a's score was higher / lower / equal to b's.
         */
        SquadPair: {
            /** A Puuid */
            a_puuid: string;
            /** B Puuid */
            b_puuid: string;
            /** Games */
            games: number;
            /** Wins */
            wins: number;
            /** Winrate */
            winrate: number;
            /** Expected Winrate */
            expected_winrate: number;
            /** Winrate Delta */
            winrate_delta: number;
            /** Avg Ai A */
            avg_ai_a: number | null;
            /** Avg Ai B */
            avg_ai_b: number | null;
            /** Scored Games */
            scored_games: number;
            /** A Higher */
            a_higher: number;
            /** B Higher */
            b_higher: number;
            /** Ties */
            ties: number;
            /** Avg Score Diff */
            avg_score_diff: number | null;
        };
        /** SquadPairs */
        SquadPairs: {
            /**
             * Since
             * @enum {string}
             */
            since: "season" | "all";
            /**
             * Season Start
             * Format: date-time
             */
            season_start: string;
            /**
             * Queue
             * @enum {string}
             */
            queue: "all" | "solo" | "flex";
            /** Model Version */
            model_version: string | null;
            /** Min Games */
            min_games: number;
            /** Players */
            players: components["schemas"]["SquadPlayer"][];
            /** Pairs */
            pairs: components["schemas"]["SquadPair"][];
        };
        /**
         * SquadPlayer
         * @description One tracked (roster) player's totals in the requested period.
         */
        SquadPlayer: {
            /** Puuid */
            puuid: string;
            /** Game Name */
            game_name: string;
            /** Tag Line */
            tag_line: string;
            /** Profile Icon Id */
            profile_icon_id: number | null;
            /** Games */
            games: number;
            /** Wins */
            wins: number;
            /** Winrate */
            winrate: number;
            /** Avg Ai Score */
            avg_ai_score: number | null;
        };
        /** StackAward */
        StackAward: {
            /**
             * Key
             * @enum {string}
             */
            key: "carry_king" | "ran_it_down" | "tried_their_best";
            /** Puuid */
            puuid: string;
            /** Count */
            count: number;
        };
        /**
         * StackGame
         * @description One team in one match on which ``size``+ roster players played together.
         */
        StackGame: {
            /** Match Id */
            match_id: string;
            /** Queue Id */
            queue_id: number;
            /** Queue Label */
            queue_label: string;
            /** Game Mode */
            game_mode: string;
            /**
             * Game Start
             * Format: date-time
             */
            game_start: string;
            /** Game Duration */
            game_duration: number;
            /** Patch */
            patch: string;
            /**
             * Team Id
             * @enum {integer}
             */
            team_id: 100 | 200;
            /** Win */
            win: boolean;
            /** Team Kills */
            team_kills: number;
            /** Enemy Kills */
            enemy_kills: number;
            /** Members */
            members: components["schemas"]["ParticipantSummary"][];
            verdict: components["schemas"]["StackVerdict"] | null;
        };
        /** StackGamePage */
        StackGamePage: {
            /** Items */
            items: components["schemas"]["StackGame"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** StackHighlight */
        StackHighlight: {
            /**
             * Key
             * @enum {string}
             */
            key: "biggest_stomp" | "worst_loss" | "longest_game" | "fastest_win" | "most_team_kills";
            /** Match Id */
            match_id: string;
            /**
             * Game Start
             * Format: date-time
             */
            game_start: string;
            /** Queue Id */
            queue_id: number;
            /** Queue Label */
            queue_label: string;
            /** Game Mode */
            game_mode: string;
            /** Win */
            win: boolean;
            /** Game Duration */
            game_duration: number;
            /** Team Kills */
            team_kills: number;
            /** Enemy Kills */
            enemy_kills: number;
            /** Member Puuids */
            member_puuids: string[];
        };
        /**
         * StackLineup
         * @description An exact set of roster players (sorted puuids) and their record together.
         */
        StackLineup: {
            /** Puuids */
            puuids: string[];
            /** Games */
            games: number;
            /** Wins */
            wins: number;
            /** Winrate */
            winrate: number;
            /**
             * Last Played
             * Format: date-time
             */
            last_played: string;
        };
        /**
         * StackPlayer
         * @description A roster player's numbers across the stacks in the requested scope.
         */
        StackPlayer: {
            /** Puuid */
            puuid: string;
            /** Game Name */
            game_name: string;
            /** Tag Line */
            tag_line: string;
            /** Profile Icon Id */
            profile_icon_id: number | null;
            /** Games */
            games: number;
            /** Wins */
            wins: number;
            /** Winrate */
            winrate: number;
            /** Avg Ai Score */
            avg_ai_score: number | null;
            /** Scored Games */
            scored_games: number;
            /** Kills */
            kills: number;
            /** Deaths */
            deaths: number;
            /** Assists */
            assists: number;
            /** Kda */
            kda: number;
            /** Hard Carries */
            hard_carries: number;
            /** Carries */
            carries: number;
            /** Ran Downs */
            ran_downs: number;
            /** Off Days */
            off_days: number;
            /** Tried */
            tried: number;
            /** Top Champion Id */
            top_champion_id: number | null;
            /** Top Champion Name */
            top_champion_name: string | null;
            /** Top Champion Games */
            top_champion_games: number;
        };
        /** StackSummary */
        StackSummary: {
            /**
             * Since
             * @enum {string}
             */
            since: "season" | "all";
            /**
             * Season Start
             * Format: date-time
             */
            season_start: string;
            /**
             * Queue
             * @enum {string}
             */
            queue: "all" | "flex";
            /** Size */
            size: number;
            /** Model Version */
            model_version: string | null;
            /** Min Lineup Games */
            min_lineup_games: number;
            /** Games */
            games: number;
            /** Wins */
            wins: number;
            /** Winrate */
            winrate: number;
            /** Recent Form */
            recent_form: boolean[];
            /** Avg Duration */
            avg_duration: number | null;
            /** Avg Team Kills */
            avg_team_kills: number | null;
            /** Avg Enemy Kills */
            avg_enemy_kills: number | null;
            /** Verdict Games */
            verdict_games: number;
            /** Players */
            players: components["schemas"]["StackPlayer"][];
            /** Lineups */
            lineups: components["schemas"]["StackLineup"][];
            best_lineup: components["schemas"]["StackLineup"] | null;
            most_played_lineup: components["schemas"]["StackLineup"] | null;
            /** Awards */
            awards: components["schemas"]["StackAward"][];
            /** Highlights */
            highlights: components["schemas"]["StackHighlight"][];
        };
        /**
         * StackVerdict
         * @description Banter verdict for one stack: teammates share the result, so their scores compare.
         */
        StackVerdict: {
            /**
             * Tier
             * @enum {string}
             */
            tier: "hardCarry" | "carry" | "edge" | "passenger" | "winTogether" | "soloLost" | "ranDown" | "offDay" | "tried" | "loseTogether";
            /** Target Puuid */
            target_puuid: string | null;
            /** Gap */
            gap: number;
        };
        /** SummonerProfile */
        SummonerProfile: {
            /** Puuid */
            puuid: string;
            /** Game Name */
            game_name: string;
            /** Tag Line */
            tag_line: string;
            /** Platform */
            platform: string;
            /** Profile Icon Id */
            profile_icon_id: number | null;
            /** Summoner Level */
            summoner_level: number | null;
            /** Is Tracked */
            is_tracked: boolean;
            /** Tracked Since */
            tracked_since: string | null;
            /** Last Refreshed At */
            last_refreshed_at: string | null;
            /** Can Refresh At */
            can_refresh_at: string | null;
            solo: components["schemas"]["RankEntry"] | null;
            flex: components["schemas"]["RankEntry"] | null;
            stats: components["schemas"]["ProfileStats"];
            /** Top Champions */
            top_champions: components["schemas"]["ChampionStat"][];
            /** Roles */
            roles: components["schemas"]["RoleStat"][];
            /** Recent Form */
            recent_form: boolean[];
            /** Main Champion */
            main_champion: string | null;
        };
        /** SummonerSearchResult */
        SummonerSearchResult: {
            /** Puuid */
            puuid: string;
            /** Game Name */
            game_name: string;
            /** Tag Line */
            tag_line: string;
            /** Profile Icon Id */
            profile_icon_id: number | null;
            /** Summoner Level */
            summoner_level: number | null;
            /** Is Tracked */
            is_tracked: boolean;
            /** Solo Tier */
            solo_tier: ("IRON" | "BRONZE" | "SILVER" | "GOLD" | "PLATINUM" | "EMERALD" | "DIAMOND" | "MASTER" | "GRANDMASTER" | "CHALLENGER") | null;
            /** Solo Rank */
            solo_rank: ("I" | "II" | "III" | "IV") | null;
        };
        /** TeamDetail */
        TeamDetail: {
            /**
             * Team Id
             * @enum {integer}
             */
            team_id: 100 | 200;
            /** Win */
            win: boolean;
            /** Kills */
            kills: number;
            /** Deaths */
            deaths: number;
            /** Assists */
            assists: number;
            /** Gold */
            gold: number;
            /** Damage To Champions */
            damage_to_champions: number;
            /** Participants */
            participants: components["schemas"]["ParticipantSummary"][];
            objectives: components["schemas"]["TeamObjectives"];
            /** Bans */
            bans: number[];
        };
        /** TeamObjectives */
        TeamObjectives: {
            baron: components["schemas"]["ObjectiveStat"];
            dragon: components["schemas"]["ObjectiveStat"];
            rift_herald: components["schemas"]["ObjectiveStat"];
            horde: components["schemas"]["ObjectiveStat"];
            tower: components["schemas"]["ObjectiveStat"];
            inhibitor: components["schemas"]["ObjectiveStat"];
            champion: components["schemas"]["ObjectiveStat"];
            atakhan: components["schemas"]["ObjectiveStat"] | null;
        };
        /** TeamSummary */
        TeamSummary: {
            /**
             * Team Id
             * @enum {integer}
             */
            team_id: 100 | 200;
            /** Win */
            win: boolean;
            /** Kills */
            kills: number;
            /** Deaths */
            deaths: number;
            /** Assists */
            assists: number;
            /** Gold */
            gold: number;
            /** Damage To Champions */
            damage_to_champions: number;
            /** Participants */
            participants: components["schemas"]["ParticipantSummary"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    get_meta: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Meta"];
                };
            };
        };
    };
    search_summoners: {
        parameters: {
            query: {
                q: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SummonerSearchResult"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_summoner_profile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Riot ID game name */
                game_name: string;
                /** @description Riot ID tag line */
                tag_line: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SummonerProfile"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Riot API rate limited (see Retry-After) */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Riot API unavailable */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Riot API key missing/rejected, or AI model not loaded */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    refresh_summoner: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Riot ID game name */
                game_name: string;
                /** @description Riot ID tag line */
                tag_line: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefreshResult"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Riot API rate limited (see Retry-After) */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Riot API unavailable */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Riot API key missing/rejected, or AI model not loaded */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_summoner_matches: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
                /** @description Filter by queue id; repeat the parameter to match any of several (e.g. queue=400&queue=430 for normals) */
                queue?: number[] | null;
            };
            header?: never;
            path: {
                puuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchPage"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_rank_history: {
        parameters: {
            query?: {
                queue?: "RANKED_SOLO_5x5" | "RANKED_FLEX_SR";
            };
            header?: never;
            path: {
                puuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RankHistory"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ai_trend: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                puuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AiTrend"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ai_explain: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                puuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AiExplain"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Riot API key missing/rejected, or AI model not loaded */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_session_insights: {
        parameters: {
            query?: {
                since?: "season" | "all";
                queue?: "all" | "solo" | "flex";
                /** @description Largest break (minutes) between one game's end and the next game's start that still counts as the same session */
                gap_minutes?: number;
            };
            header?: never;
            path: {
                puuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionInsights"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_schedule_insights: {
        parameters: {
            query?: {
                since?: "season" | "all";
                queue?: "all" | "solo" | "flex";
                /** @description IANA time zone for day of week / hour (the browser's zone) */
                tz?: string;
            };
            header?: never;
            path: {
                puuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduleInsights"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_matchup_insights: {
        parameters: {
            query?: {
                since?: "season" | "all";
                queue?: "all" | "solo" | "flex";
                /** @description Fewest games against a champion to list it */
                min_games?: number;
            };
            header?: never;
            path: {
                puuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchupInsights"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_luck_insights: {
        parameters: {
            query?: {
                since?: "season" | "all";
                queue?: "all" | "solo" | "flex";
                /** @description Games per list */
                limit?: number;
            };
            header?: never;
            path: {
                puuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LuckInsights"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_match: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                match_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchDetail"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_leaderboard: {
        parameters: {
            query?: {
                queue?: "all" | "solo" | "flex";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Leaderboard"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_roster: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RosterEntry"][];
                };
            };
        };
    };
    add_roster_entry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_name: string;
                tag_line: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RosterEntry"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Missing admin token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid admin token */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Riot API rate limited (see Retry-After) */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Riot API unavailable */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Riot API key missing/rejected, or AI model not loaded */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    remove_roster_entry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_name: string;
                tag_line: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Missing admin token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid admin token */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_squad_pairs: {
        parameters: {
            query?: {
                since?: "season" | "all";
                queue?: "all" | "solo" | "flex";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SquadPairs"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_stack_summary: {
        parameters: {
            query?: {
                since?: "season" | "all";
                queue?: "all" | "flex";
                /** @description Fewest roster players on one team */
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StackSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_stack_games: {
        parameters: {
            query?: {
                since?: "season" | "all";
                queue?: "all" | "flex";
                /** @description Fewest roster players on one team */
                size?: number;
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StackGamePage"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_recent_games: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StackGamePage"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_live_games: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LiveGames"];
                };
            };
        };
    };
    get_records: {
        parameters: {
            query?: {
                since?: "season" | "all";
                queue?: "all" | "solo" | "flex";
                /** @description Only this player's games (scope 'player'); omit for the roster */
                puuid?: string | null;
                /** @description Entries per category */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Records"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
