/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Service health */
        get: operations["get_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Data Dragon version, region, queues */
        get: operations["get_meta"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search known summoners by game name (accepts 'Name#TAG'); tracked players first */
        get: operations["search_summoners"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/summoners/by-riot-id/{game_name}/{tag_line}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Profile by Riot ID (resolves unknown players through Riot) */
        get: operations["get_summoner_profile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/summoners/by-riot-id/{game_name}/{tag_line}/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Update button: refresh rank and ingest new matches (rate limited per player) */
        post: operations["refresh_summoner"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/summoners/{puuid}/matches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Match history, newest first (cursor paginated) */
        get: operations["list_summoner_matches"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/summoners/{puuid}/ranks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Rank snapshots for one queue, oldest first */
        get: operations["get_rank_history"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/summoners/{puuid}/ai-trend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stored AI scores over recent games (works without a loaded model) */
        get: operations["get_ai_trend"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/summoners/{puuid}/ai-explain": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Which stats drive this player's AI Score (gradient x input) */
        get: operations["get_ai_explain"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/matches/{match_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Both teams, objectives, bans and AI scores for one stored match */
        get: operations["get_match"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/leaderboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Season leaderboard of the tracked roster */
        get: operations["get_leaderboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/roster": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Tracked players */
        get: operations["list_roster"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/roster/{game_name}/{tag_line}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Start tracking a player (admin) */
        put: operations["add_roster_entry"];
        post?: never;
        /** Stop tracking a player (admin); match data is kept */
        delete: operations["remove_roster_entry"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AiExplain */
        AiExplain: {
            /** Puuid */
            puuid: string;
            /** Model Version */
            model_version: string;
            /** N Matches */
            n_matches: number;
            /** Base Score */
            base_score: number | null;
            /** Features */
            features: components["schemas"]["FeatureAttribution"][];
        };
        /** AiTrend */
        AiTrend: {
            /** Puuid */
            puuid: string;
            /** Model Version */
            model_version: string | null;
            /** Average */
            average: number | null;
            /** Points */
            points: components["schemas"]["AiTrendPoint"][];
        };
        /** AiTrendPoint */
        AiTrendPoint: {
            /** Match Id */
            match_id: string;
            /**
             * Game Start
             * Format: date-time
             */
            game_start: string;
            /** Champion Name */
            champion_name: string;
            /** Win */
            win: boolean;
            /** Ai Score */
            ai_score: number;
        };
        /** BestAlly */
        BestAlly: {
            /** Puuid */
            puuid: string;
            /** Game Name */
            game_name: string;
            /** Tag Line */
            tag_line: string;
            /** Games */
            games: number;
            /** Wins */
            wins: number;
            /** Winrate */
            winrate: number;
        };
        /** ChampionStat */
        ChampionStat: {
            /** Champion Id */
            champion_id: number;
            /** Champion Name */
            champion_name: string;
            /** Games */
            games: number;
            /** Wins */
            wins: number;
            /** Winrate */
            winrate: number;
            /** Kda */
            kda: number;
            /** Avg Ai Score */
            avg_ai_score: number | null;
        };
        /** ErrorResponse */
        ErrorResponse: {
            /** Detail */
            detail: string;
            /** Code */
            code: string | null;
        };
        /** FeatureAttribution */
        FeatureAttribution: {
            /** Feature */
            feature: string;
            /** Label */
            label: string;
            /**
             * Group
             * @enum {string}
             */
            group: "combat" | "economy" | "vision" | "objectives" | "survival" | "teamplay";
            /** Mean Attribution */
            mean_attribution: number;
            /** Mean Abs Attribution */
            mean_abs_attribution: number;
            /** Player Value */
            player_value: number;
            /** Population Value */
            population_value: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
            /** Version */
            version: string;
            /** Db Ok */
            db_ok: boolean;
            model: components["schemas"]["HealthModel"];
            riot: components["schemas"]["HealthRiot"];
            poller: components["schemas"]["HealthPoller"];
            bot: components["schemas"]["HealthBot"];
        };
        /** HealthBot */
        HealthBot: {
            /** Configured */
            configured: boolean;
            /** Running */
            running: boolean;
            /** Connected */
            connected: boolean;
            /** Heartbeat At */
            heartbeat_at: string | null;
            /** Last Error */
            last_error: string | null;
        };
        /** HealthModel */
        HealthModel: {
            /** Loaded */
            loaded: boolean;
            /** Version */
            version: string | null;
            /** Trained At */
            trained_at: string | null;
            /** N Features */
            n_features: number | null;
        };
        /** HealthPoller */
        HealthPoller: {
            /** Last Run At */
            last_run_at: string | null;
            /** Last Error */
            last_error: string | null;
            /** Running */
            running: boolean;
        };
        /** HealthRiot */
        HealthRiot: {
            /** Key Configured */
            key_configured: boolean;
            /** Key Ok */
            key_ok: boolean | null;
            /** Last Error */
            last_error: string | null;
        };
        /** Leaderboard */
        Leaderboard: {
            /**
             * Season Start
             * Format: date-time
             */
            season_start: string;
            /** Model Version */
            model_version: string | null;
            /**
             * Queue
             * @enum {string}
             */
            queue: "all" | "solo" | "flex";
            /** Entries */
            entries: components["schemas"]["LeaderboardEntry"][];
        };
        /** LeaderboardEntry */
        LeaderboardEntry: {
            /** Puuid */
            puuid: string;
            /** Game Name */
            game_name: string;
            /** Tag Line */
            tag_line: string;
            /** Profile Icon Id */
            profile_icon_id: number | null;
            /** Summoner Level */
            summoner_level: number | null;
            solo: components["schemas"]["RankEntry"] | null;
            flex: components["schemas"]["RankEntry"] | null;
            /** Games */
            games: number;
            /** Wins */
            wins: number;
            /** Losses */
            losses: number;
            /** Winrate */
            winrate: number;
            /** Kda */
            kda: number;
            /** Avg Kills */
            avg_kills: number;
            /** Avg Deaths */
            avg_deaths: number;
            /** Avg Assists */
            avg_assists: number;
            /** Avg Ai Score */
            avg_ai_score: number | null;
            /** Lp Delta */
            lp_delta: number | null;
            best_ally: components["schemas"]["BestAlly"] | null;
            /** Top Champions */
            top_champions: string[];
            /** Recent Form */
            recent_form: boolean[];
        };
        /** MatchDetail */
        MatchDetail: {
            /** Match Id */
            match_id: string;
            /** Queue Id */
            queue_id: number;
            /** Queue Label */
            queue_label: string;
            /** Game Mode */
            game_mode: string;
            /** Game Version */
            game_version: string;
            /** Patch */
            patch: string;
            /**
             * Game Start
             * Format: date-time
             */
            game_start: string;
            /** Game Duration */
            game_duration: number;
            /** Remake */
            remake: boolean;
            /** Model Version */
            model_version: string | null;
            /** Teams */
            teams: components["schemas"]["TeamDetail"][];
        };
        /** MatchPage */
        MatchPage: {
            /** Items */
            items: components["schemas"]["MatchSummary"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** MatchSummary */
        MatchSummary: {
            /** Match Id */
            match_id: string;
            /** Queue Id */
            queue_id: number;
            /** Queue Label */
            queue_label: string;
            /** Game Mode */
            game_mode: string;
            /**
             * Game Start
             * Format: date-time
             */
            game_start: string;
            /** Game Duration */
            game_duration: number;
            /** Patch */
            patch: string;
            /** Remake */
            remake: boolean;
            me: components["schemas"]["ParticipantSummary"];
            /** Teams */
            teams: components["schemas"]["TeamSummary"][];
        };
        /** Meta */
        Meta: {
            /** Ddragon Version */
            ddragon_version: string;
            /** Ddragon Cdn */
            ddragon_cdn: string;
            /** Platform */
            platform: string;
            /** Region */
            region: string;
            /**
             * Season Start
             * Format: date-time
             */
            season_start: string;
            /** Model Version */
            model_version: string | null;
            /** Model Trained At */
            model_trained_at: string | null;
            /** Queues */
            queues: {
                [key: string]: string;
            };
        };
        /** ObjectiveStat */
        ObjectiveStat: {
            /** First */
            first: boolean;
            /** Kills */
            kills: number;
        };
        /** ParticipantSummary */
        ParticipantSummary: {
            /** Puuid */
            puuid: string;
            /** Game Name */
            game_name: string | null;
            /** Tag Line */
            tag_line: string | null;
            /** Participant Id */
            participant_id: number;
            /**
             * Team Id
             * @enum {integer}
             */
            team_id: 100 | 200;
            /** Subteam Id */
            subteam_id: number | null;
            /** Placement */
            placement: number | null;
            /**
             * Team Position
             * @enum {string}
             */
            team_position: "TOP" | "JUNGLE" | "MIDDLE" | "BOTTOM" | "UTILITY" | "UNKNOWN";
            /** Champion Id */
            champion_id: number;
            /** Champion Name */
            champion_name: string;
            /** Champ Level */
            champ_level: number;
            /** Win */
            win: boolean;
            /** Kills */
            kills: number;
            /** Deaths */
            deaths: number;
            /** Assists */
            assists: number;
            /** Kda */
            kda: number;
            /** Kill Participation */
            kill_participation: number;
            /** Cs */
            cs: number;
            /** Cs Per Min */
            cs_per_min: number;
            /** Gold */
            gold: number;
            /** Gold Per Min */
            gold_per_min: number;
            /** Damage To Champions */
            damage_to_champions: number;
            /** Damage Per Min */
            damage_per_min: number;
            /** Damage Taken */
            damage_taken: number;
            /** Vision Score */
            vision_score: number;
            /** Wards Placed */
            wards_placed: number;
            /** Wards Killed */
            wards_killed: number;
            /** Control Wards */
            control_wards: number;
            /** Items */
            items: number[];
            /** Summoner1 Id */
            summoner1_id: number;
            /** Summoner2 Id */
            summoner2_id: number;
            /** Largest Multikill */
            largest_multikill: number;
            /** Ai Score */
            ai_score: number | null;
            /** Ai Rank */
            ai_rank: number | null;
            /** Is Tracked */
            is_tracked: boolean;
        };
        /**
         * ProfileStats
         * @description Season aggregates over ranked queues (420, 440), remakes excluded.
         */
        ProfileStats: {
            /** Games */
            games: number;
            /** Wins */
            wins: number;
            /** Losses */
            losses: number;
            /** Winrate */
            winrate: number;
            /** Avg Kills */
            avg_kills: number;
            /** Avg Deaths */
            avg_deaths: number;
            /** Avg Assists */
            avg_assists: number;
            /** Kda */
            kda: number;
            /** Avg Cs Per Min */
            avg_cs_per_min: number;
            /** Avg Damage Per Min */
            avg_damage_per_min: number;
            /** Avg Vision Per Min */
            avg_vision_per_min: number;
            /** Avg Kill Participation */
            avg_kill_participation: number;
            /** Avg Ai Score */
            avg_ai_score: number | null;
            /** Ai Scored Games */
            ai_scored_games: number;
        };
        /** RankEntry */
        RankEntry: {
            /**
             * Queue Type
             * @enum {string}
             */
            queue_type: "RANKED_SOLO_5x5" | "RANKED_FLEX_SR";
            /**
             * Tier
             * @enum {string}
             */
            tier: "IRON" | "BRONZE" | "SILVER" | "GOLD" | "PLATINUM" | "EMERALD" | "DIAMOND" | "MASTER" | "GRANDMASTER" | "CHALLENGER";
            /** Rank */
            rank: ("I" | "II" | "III" | "IV") | null;
            /** Lp */
            lp: number;
            /** Wins */
            wins: number;
            /** Losses */
            losses: number;
            /** Winrate */
            winrate: number;
            /** Rank Value */
            rank_value: number;
            /**
             * Taken At
             * Format: date-time
             */
            taken_at: string;
        };
        /** RankHistory */
        RankHistory: {
            /** Puuid */
            puuid: string;
            /**
             * Queue Type
             * @enum {string}
             */
            queue_type: "RANKED_SOLO_5x5" | "RANKED_FLEX_SR";
            /** Points */
            points: components["schemas"]["RankPoint"][];
        };
        /** RankPoint */
        RankPoint: {
            /**
             * Taken At
             * Format: date-time
             */
            taken_at: string;
            /**
             * Tier
             * @enum {string}
             */
            tier: "IRON" | "BRONZE" | "SILVER" | "GOLD" | "PLATINUM" | "EMERALD" | "DIAMOND" | "MASTER" | "GRANDMASTER" | "CHALLENGER";
            /** Rank */
            rank: ("I" | "II" | "III" | "IV") | null;
            /** Lp */
            lp: number;
            /** Rank Value */
            rank_value: number;
            /** Wins */
            wins: number;
            /** Losses */
            losses: number;
        };
        /** RefreshResult */
        RefreshResult: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "cooldown" | "partial" | "unavailable";
            /** New Matches */
            new_matches: number;
            /** Pending */
            pending: number;
            /**
             * Next Allowed At
             * Format: date-time
             */
            next_allowed_at: string;
            /** Message */
            message: string;
            profile: components["schemas"]["SummonerProfile"];
        };
        /** RoleStat */
        RoleStat: {
            /**
             * Position
             * @enum {string}
             */
            position: "TOP" | "JUNGLE" | "MIDDLE" | "BOTTOM" | "UTILITY" | "UNKNOWN";
            /** Games */
            games: number;
            /** Wins */
            wins: number;
            /** Winrate */
            winrate: number;
        };
        /** RosterEntry */
        RosterEntry: {
            /** Puuid */
            puuid: string;
            /** Game Name */
            game_name: string;
            /** Tag Line */
            tag_line: string;
            /** Tracked Since */
            tracked_since: string | null;
            /** Profile Icon Id */
            profile_icon_id: number | null;
        };
        /** SummonerProfile */
        SummonerProfile: {
            /** Puuid */
            puuid: string;
            /** Game Name */
            game_name: string;
            /** Tag Line */
            tag_line: string;
            /** Platform */
            platform: string;
            /** Profile Icon Id */
            profile_icon_id: number | null;
            /** Summoner Level */
            summoner_level: number | null;
            /** Is Tracked */
            is_tracked: boolean;
            /** Tracked Since */
            tracked_since: string | null;
            /** Last Refreshed At */
            last_refreshed_at: string | null;
            /** Can Refresh At */
            can_refresh_at: string | null;
            solo: components["schemas"]["RankEntry"] | null;
            flex: components["schemas"]["RankEntry"] | null;
            stats: components["schemas"]["ProfileStats"];
            /** Top Champions */
            top_champions: components["schemas"]["ChampionStat"][];
            /** Roles */
            roles: components["schemas"]["RoleStat"][];
            /** Recent Form */
            recent_form: boolean[];
            /** Main Champion */
            main_champion: string | null;
        };
        /** SummonerSearchResult */
        SummonerSearchResult: {
            /** Puuid */
            puuid: string;
            /** Game Name */
            game_name: string;
            /** Tag Line */
            tag_line: string;
            /** Profile Icon Id */
            profile_icon_id: number | null;
            /** Summoner Level */
            summoner_level: number | null;
            /** Is Tracked */
            is_tracked: boolean;
            /** Solo Tier */
            solo_tier: ("IRON" | "BRONZE" | "SILVER" | "GOLD" | "PLATINUM" | "EMERALD" | "DIAMOND" | "MASTER" | "GRANDMASTER" | "CHALLENGER") | null;
            /** Solo Rank */
            solo_rank: ("I" | "II" | "III" | "IV") | null;
        };
        /** TeamDetail */
        TeamDetail: {
            /**
             * Team Id
             * @enum {integer}
             */
            team_id: 100 | 200;
            /** Win */
            win: boolean;
            /** Kills */
            kills: number;
            /** Deaths */
            deaths: number;
            /** Assists */
            assists: number;
            /** Gold */
            gold: number;
            /** Damage To Champions */
            damage_to_champions: number;
            /** Participants */
            participants: components["schemas"]["ParticipantSummary"][];
            objectives: components["schemas"]["TeamObjectives"];
            /** Bans */
            bans: number[];
        };
        /** TeamObjectives */
        TeamObjectives: {
            baron: components["schemas"]["ObjectiveStat"];
            dragon: components["schemas"]["ObjectiveStat"];
            rift_herald: components["schemas"]["ObjectiveStat"];
            horde: components["schemas"]["ObjectiveStat"];
            tower: components["schemas"]["ObjectiveStat"];
            inhibitor: components["schemas"]["ObjectiveStat"];
            champion: components["schemas"]["ObjectiveStat"];
            atakhan: components["schemas"]["ObjectiveStat"] | null;
        };
        /** TeamSummary */
        TeamSummary: {
            /**
             * Team Id
             * @enum {integer}
             */
            team_id: 100 | 200;
            /** Win */
            win: boolean;
            /** Kills */
            kills: number;
            /** Deaths */
            deaths: number;
            /** Assists */
            assists: number;
            /** Gold */
            gold: number;
            /** Damage To Champions */
            damage_to_champions: number;
            /** Participants */
            participants: components["schemas"]["ParticipantSummary"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    get_meta: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Meta"];
                };
            };
        };
    };
    search_summoners: {
        parameters: {
            query: {
                q: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SummonerSearchResult"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_summoner_profile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Riot ID game name */
                game_name: string;
                /** @description Riot ID tag line */
                tag_line: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SummonerProfile"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Riot API rate limited (see Retry-After) */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Riot API unavailable */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Riot API key missing/rejected, or AI model not loaded */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    refresh_summoner: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Riot ID game name */
                game_name: string;
                /** @description Riot ID tag line */
                tag_line: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefreshResult"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Riot API rate limited (see Retry-After) */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Riot API unavailable */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Riot API key missing/rejected, or AI model not loaded */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_summoner_matches: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
                /** @description Filter by queue id; repeat the parameter to match any of several (e.g. queue=400&queue=430 for normals) */
                queue?: number[] | null;
            };
            header?: never;
            path: {
                puuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchPage"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_rank_history: {
        parameters: {
            query?: {
                queue?: "RANKED_SOLO_5x5" | "RANKED_FLEX_SR";
            };
            header?: never;
            path: {
                puuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RankHistory"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ai_trend: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                puuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AiTrend"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ai_explain: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                puuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AiExplain"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Riot API key missing/rejected, or AI model not loaded */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_match: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                match_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchDetail"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_leaderboard: {
        parameters: {
            query?: {
                queue?: "all" | "solo" | "flex";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Leaderboard"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_roster: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RosterEntry"][];
                };
            };
        };
    };
    add_roster_entry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_name: string;
                tag_line: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RosterEntry"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Missing admin token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid admin token */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Riot API rate limited (see Retry-After) */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Riot API unavailable */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Riot API key missing/rejected, or AI model not loaded */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    remove_roster_entry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_name: string;
                tag_line: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Missing admin token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid admin token */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
