"""Seed a realistic synthetic dataset through the real ingestion path (owner: B6).

There is no Riot API key in development, so the web UI is built and demoed against data made
here. :func:`build_dataset` is pure and deterministic (``random.Random(seed)`` plus a fixed
``now``); :func:`seed_demo` writes it:

* a tracked roster (:data:`hextrack.demo.names.ROSTER`) of eight friends who often queue
  together (bot-lane duos, flex stacks of 3 or 5), with distinct skill levels, plus a few
  hundred strangers who fill the other slots and keep meeting the roster again;
* ``matches`` ranked games (mostly solo/duo 420, some flex 440) over the last ~100 days in
  evening sessions (laid out relative to the latest 05:00 UTC, so a seed yields the same
  games whenever it runs; only whole-day shifts differ), generated by
  :func:`hextrack.demo.matchgen.generate_match` and stored with
  ``hextrack.ingest.service.ingest_match_json(enqueue_events=False)``, so validation, storage
  and AI scoring (when a model is loaded) are exactly those of live ingestion;
* rank snapshots that follow each tracked player's actual wins and losses: LP gains/losses
  per game, promotions, demotions (with a short demotion shield), a snapshot after every ranked
  game as the poller would take it and a heartbeat every day or two in between.

Everything demo-generated is recognisable: match ids start with ``DEMO_`` and puuids with
``demo-``. ``reset=True`` deletes exactly that data (and bot events that refer to it) and
nothing else, so demo data can live next to real data.
"""

from __future__ import annotations

import logging
import random
from collections import deque
from collections.abc import Collection, Sequence
from dataclasses import dataclass, field, replace
from datetime import UTC, datetime, time, timedelta
from pathlib import Path
from typing import TYPE_CHECKING, Any, Final, Literal

from sqlalchemy import delete, func, or_, select, tuple_
from sqlalchemy.dialects.postgresql import insert
from sqlalchemy.ext.asyncio import AsyncSession

from hextrack.config import Settings
from hextrack.db.engine import make_async_engine, make_session_factory
from hextrack.db.models import BotEvent, Match, MatchParticipant, RankSnapshot, Summoner
from hextrack.demo.matchgen import (
    BLUE,
    CHAMPIONS_BY_KEY,
    CHAMPIONS_BY_ROLE,
    DEMO_MATCH_PREFIX,
    MAX_GAME_SECONDS,
    MIN_GAME_SECONDS,
    RED,
    ROLES,
    MatchPlan,
    Role,
    Slot,
    generate_match,
)
from hextrack.demo.names import (
    DEMO_PUUID_PREFIX,
    DUO_AFFINITY,
    ROSTER,
    Opponent,
    RosterPlayer,
    extra_roster_player,
    make_opponents,
    validate_roster,
)
from hextrack.ingest.context import IngestContext
from hextrack.ingest.service import ingest_match_json
from hextrack.rank import (
    APEX_TIERS,
    DIVISION_ORDER,
    MASTER_BASE,
    RANKED_FLEX_SR,
    TIER_ORDER,
    RANKED_SOLO_5x5,
    rank_value,
)
from hextrack.riot.client import RiotClient
from hextrack.riotid import riot_id_key

if TYPE_CHECKING:
    from hextrack.hextrack_ai.inference import Scorer

logger = logging.getLogger(__name__)

#: How far back the generated games go.
WINDOW_DAYS: Final = 100
SOLO_QUEUE: Final = 420
FLEX_QUEUE: Final = 440
#: Share of games that are remakes (never scorable, no LP change).
REMAKE_RATE: Final = 0.01
#: Commit every N ingested matches.
COMMIT_EVERY: Final = 25
#: Win probability shift per point of (tracked) player skill on a team.
TRACKED_SKILL_WEIGHT: Final = 0.14
OPPONENT_SKILL_WEIGHT: Final = 0.05
#: Sessions are over by this hour (UTC) = 11 pm / midnight in US Central time.
SESSION_DAY_END_HOUR: Final = 5
#: Win probability shift per net win over a player's last :data:`FORM_GAMES` games; this is
#: matchmaking pulling streaky players back towards 50%.
FORM_WEIGHT: Final = 0.012
FORM_GAMES: Final = 10
#: Grandmaster promotion / demotion thresholds in Master LP (demo ladder).
GRANDMASTER_LP: Final = 350
GRANDMASTER_KEEP_LP: Final = 250

SessionKind = Literal["solo", "duo", "rivals", "flex"]


@dataclass(slots=True)
class SeedReport:
    """What :func:`seed_demo` did.

    ``players`` / ``opponents`` are the tracked and untracked demo summoners in the dataset;
    ``matches``, ``participants`` and ``rank_snapshots`` count rows created by this run (a
    second run without ``reset`` creates nothing new).
    """

    players: int
    matches: int
    participants: int
    rank_snapshots: int
    reset: bool
    opponents: int = 0
    scored_matches: int = 0
    deleted_matches: int = 0


# --- dataset (pure) --------------------------------------------------------------------------


@dataclass(frozen=True, slots=True)
class DemoSummoner:
    puuid: str
    game_name: str
    tag_line: str
    profile_icon_id: int
    summoner_level: int
    is_tracked: bool
    tracked_since: datetime | None
    last_refreshed_at: datetime | None
    backfilled_at: datetime | None


@dataclass(frozen=True, slots=True)
class DemoSnapshot:
    puuid: str
    queue_type: str
    tier: str
    rank: str | None
    lp: int
    wins: int
    losses: int
    rank_value: int
    taken_at: datetime
    is_heartbeat: bool


@dataclass(slots=True)
class DemoDataset:
    now: datetime
    summoners: list[DemoSummoner]
    #: Raw match-v5 payloads, oldest first.
    matches: list[dict[str, Any]]
    snapshots: list[DemoSnapshot]

    @property
    def tracked(self) -> list[DemoSummoner]:
        return [s for s in self.summoners if s.is_tracked]


@dataclass(slots=True)
class _Ladder:
    """One player's standing in one ranked queue, updated game by game."""

    tier: str
    rank: str | None
    lp: int
    wins: int
    losses: int
    shield: int = 0

    @property
    def value(self) -> int:
        return rank_value(self.tier, self.rank, self.lp)

    def snapshot(self, puuid: str, queue_type: str, at: datetime, heartbeat: bool) -> DemoSnapshot:
        return DemoSnapshot(
            puuid=puuid,
            queue_type=queue_type,
            tier=self.tier,
            rank=self.rank,
            lp=self.lp,
            wins=self.wins,
            losses=self.losses,
            rank_value=self.value,
            taken_at=at,
            is_heartbeat=heartbeat,
        )

    def apply(self, win: bool, gain: int, loss: int) -> None:
        if win:
            self.wins += 1
            self._win(gain)
        else:
            self.losses += 1
            self._lose(loss)
        self.shield = max(0, self.shield - 1)

    def _win(self, gain: int) -> None:
        self.lp += gain
        if self.tier in APEX_TIERS:
            if self.tier == "MASTER" and self.lp >= GRANDMASTER_LP:
                self.tier = "GRANDMASTER"
            return
        if self.lp < 100:
            return
        self.lp -= 100
        self.shield = 3
        assert self.rank is not None
        division = DIVISION_ORDER.index(self.rank)
        if division < len(DIVISION_ORDER) - 1:
            self.rank = DIVISION_ORDER[division + 1]
            return
        next_tier = TIER_ORDER[TIER_ORDER.index(self.tier) + 1]
        self.tier = next_tier
        self.rank = None if next_tier in APEX_TIERS else DIVISION_ORDER[0]

    def _lose(self, loss: int) -> None:
        if self.tier in APEX_TIERS:
            if self.lp == 0 and self.shield == 0:
                self.tier, self.rank, self.lp = "DIAMOND", "I", 75
                return
            self.lp = max(0, self.lp - loss)
            if self.tier == "GRANDMASTER" and self.lp < GRANDMASTER_KEEP_LP:
                self.tier = "MASTER"
            return
        if self.lp > 0 or self.shield > 0:
            self.lp = max(0, self.lp - loss)
            return
        assert self.rank is not None
        division = DIVISION_ORDER.index(self.rank)
        if division > 0:
            self.rank = DIVISION_ORDER[division - 1]
            self.lp = 75
        elif self.tier != TIER_ORDER[0]:
            self.tier = TIER_ORDER[TIER_ORDER.index(self.tier) - 1]
            self.rank = DIVISION_ORDER[-1]
            self.lp = 75


def standing_for_value(value: int) -> tuple[str, str | None, int]:
    """Inverse of :func:`hextrack.rank.rank_value` (Master+ collapses onto MASTER)."""
    value = max(0, value)
    if value >= MASTER_BASE:
        return "MASTER", None, value - MASTER_BASE
    tier = TIER_ORDER[value // 400]
    rank = DIVISION_ORDER[(value % 400) // 100]
    return tier, rank, value % 100


@dataclass(slots=True)
class _Member:
    """A tracked player plus their mutable ladder state during generation."""

    index: int
    player: RosterPlayer
    puuid: str
    solo: _Ladder
    flex: _Ladder | None
    busy: list[tuple[datetime, datetime]] = field(default_factory=list)


@dataclass(slots=True)
class _Game:
    start: datetime
    duration_s: int
    queue_id: int
    remake: bool
    #: Roster indices on the roster's side.
    allies: list[int]
    #: Roster indices on the other side ("rivals" games only).
    rivals: list[int] = field(default_factory=list)

    @property
    def end(self) -> datetime:
        return self.start + timedelta(seconds=self.duration_s)


def _weighted_choice[T](rng: random.Random, options: Sequence[tuple[T, float]]) -> T:
    total = sum(w for _, w in options)
    pick = rng.random() * total
    for value, weight in options:
        pick -= weight
        if pick <= 0:
            return value
    return options[-1][0]


def _duration(rng: random.Random) -> int:
    """18-42 minutes: early surrenders, a bulk around 30 minutes and a long tail."""
    if rng.random() < 0.28:
        seconds = rng.uniform(18 * 60, 26.5 * 60)
    else:
        seconds = rng.gauss(31 * 60, 4.5 * 60)
    return int(min(MAX_GAME_SECONDS, max(MIN_GAME_SECONDS, seconds)))


#: Tags tried, in order, when a roster Riot ID already belongs to a real account.
FALLBACK_TAGS: Final[tuple[str, ...]] = ("DEMO", "DEMO2", "DEMO3", "DEMO4", "DEMO5")


def _build_roster(
    rng: random.Random, players: int, taken: set[tuple[str, str]]
) -> list[RosterPlayer]:
    """The first ``players`` roster entries (plus generated extras). A roster Riot ID that is
    already in ``taken`` (a real account) keeps its name but gets a ``DEMO`` tag."""
    roster: list[RosterPlayer] = []
    for p in ROSTER[:players]:
        if riot_id_key(p.game_name, p.tag_line) in taken:
            tag = next((t for t in FALLBACK_TAGS if riot_id_key(p.game_name, t) not in taken), None)
            if tag is None:
                raise ValueError(f"no free demo Riot ID for {p.riot_id}")
            logger.warning(
                "%s belongs to a real account; the demo uses %s#%s", p.riot_id, p.game_name, tag
            )
            p = replace(p, tag_line=tag)
        taken.add(riot_id_key(p.game_name, p.tag_line))
        roster.append(p)
    while len(roster) < players:
        extra = make_opponents(rng, 1, rank_range=(0, 1), taken=taken)[0]
        roster.append(extra_roster_player(rng, extra.game_name, extra.tag_line))
    return roster


def _initial_ladders(rng: random.Random, player: RosterPlayer) -> tuple[_Ladder, _Ladder | None]:
    base_games = rng.randint(70, 190)
    base_wins = round(base_games * (0.5 + 0.03 * player.skill + rng.gauss(0.0, 0.01)))
    solo = _Ladder(
        player.start_tier,
        None if player.start_tier in APEX_TIERS else player.start_rank,
        player.start_lp,
        base_wins,
        base_games - base_wins,
    )
    if not player.plays_flex:
        return solo, None
    flex_value = max(0, solo.value - rng.randint(50, 350))
    tier, rank, lp = standing_for_value(flex_value)
    flex_games = rng.randint(8, 50)
    flex_wins = round(flex_games * rng.uniform(0.44, 0.58))
    return solo, _Ladder(tier, rank, lp, flex_wins, flex_games - flex_wins)


def _overlaps(busy: Sequence[tuple[datetime, datetime]], start: datetime, end: datetime) -> bool:
    return any(start < b_end and b_start < end for b_start, b_end in busy)


def _pick_members(rng: random.Random, members: list[_Member], kind: SessionKind) -> list[_Member]:
    eligible = [m for m in members if m.flex is not None] if kind == "flex" else members
    leader = _weighted_choice(rng, [(m, m.player.activity) for m in eligible])
    if kind == "solo" or len(eligible) == 1:
        return [leader]
    wanted = 2
    pool = [m for m in eligible if m is not leader]
    if kind == "flex":
        wanted = _weighted_choice(rng, [(2, 0.25), (3, 0.45), (5, 0.3)])
    chosen = [leader]
    while len(chosen) < wanted and pool:
        weights = []
        for m in pool:
            affinity = max(DUO_AFFINITY.get(frozenset({c.index, m.index}), 1.0) for c in chosen)
            weights.append((m, m.player.activity * affinity))
        pick = _weighted_choice(rng, weights)
        chosen.append(pick)
        pool.remove(pick)
    return chosen


def schedule_anchor(now: datetime) -> datetime:
    """The latest 05:00 UTC at or before ``now`` (after the NA evening, when sessions end).

    Games are laid out relative to this instant, so a seed yields the same games whatever
    the time of day; running on another day only shifts every timestamp by whole days.
    """
    anchor = datetime.combine(now.astimezone(UTC).date(), time(SESSION_DAY_END_HOUR), UTC)
    return anchor if anchor <= now else anchor - timedelta(days=1)


def _schedule(
    rng: random.Random, members: list[_Member], matches: int, anchor: datetime
) -> list[_Game]:
    """Evening sessions (1-5 games back to back) spread over the window, no overlaps."""
    first_day = anchor - timedelta(days=WINDOW_DAYS, hours=SESSION_DAY_END_HOUR)
    window_start = first_day
    latest_end = anchor
    games: list[_Game] = []
    flex_ok = sum(1 for m in members if m.flex is not None) >= 2
    kinds: list[tuple[SessionKind, float]] = [("solo", 0.36), ("duo", 0.38), ("rivals", 0.02)]
    if flex_ok:
        kinds.append(("flex", 0.21))
    failures = 0
    while len(games) < matches:
        if failures > 500:
            raise ValueError(
                f"cannot fit {matches} games for {len(members)} players into {WINDOW_DAYS} days"
            )
        kind = _weighted_choice(rng, kinds) if len(members) > 1 else "solo"
        group = _pick_members(rng, members, kind)
        if kind == "rivals" and len(group) < 2:
            kind = "solo"
        n_games = (
            1
            if kind == "rivals"
            else _weighted_choice(rng, [(1, 0.3), (2, 0.3), (3, 0.2), (4, 0.12), (5, 0.08)])
        )
        n_games = min(n_games, matches - len(games))
        queue = FLEX_QUEUE if kind == "flex" else SOLO_QUEUE
        placed = False
        for _attempt in range(80):
            day = rng.randrange(WINDOW_DAYS + 1)
            # Two days a week the group also plays in the afternoon (a fixed pattern, so the
            # schedule does not depend on the calendar).
            weekend = day % 7 in (5, 6)
            hour = rng.uniform(15.0 if weekend else 22.0, 28.5)
            start = first_day + timedelta(days=day, hours=hour)
            start = start.replace(second=0, microsecond=0) + timedelta(seconds=rng.randint(0, 59))
            session: list[_Game] = []
            cursor = start
            for _ in range(n_games):
                duration = _duration(rng)
                allies = [m.index for m in group]
                rivals: list[int] = []
                if kind == "rivals":
                    allies, rivals = allies[:1], allies[1:2]
                session.append(_Game(cursor, duration, queue, False, allies, rivals))
                cursor = cursor + timedelta(seconds=duration) + timedelta(minutes=rng.uniform(3, 9))
            s_start, s_end = session[0].start, session[-1].end
            if s_start < window_start or s_end > latest_end:
                continue
            margin = timedelta(minutes=2)
            if any(_overlaps(m.busy, s_start - margin, s_end + margin) for m in group):
                continue
            for m in group:
                m.busy.append((s_start, s_end))
            games.extend(session)
            placed = True
            break
        if not placed:
            failures += 1
    games.sort(key=lambda g: g.start)
    # ~1% remakes on fixed, deterministic positions (only when there are enough games).
    n_remakes = max(1, round(len(games) * REMAKE_RATE)) if len(games) >= 50 else 0
    for idx in rng.sample(range(len(games)), n_remakes):
        games[idx].remake = True
        games[idx].duration_s = rng.randint(190, 290)
    return games


@dataclass(slots=True)
class _OpponentState:
    opponent: Opponent
    puuid: str
    free_at: datetime
    appearances: int = 0
    last_end: datetime | None = None


def _assign_roles(rng: random.Random, players: list[RosterPlayer], taken: set[Role]) -> list[Role]:
    roles: list[Role] = []
    for p in players:
        prefs: list[Role] = (
            [p.main_role, p.secondary_role]
            if rng.random() < 0.85
            else [p.secondary_role, p.main_role]
        )
        free = [r for r in prefs if r not in taken]
        if free:
            role = free[0]
        else:
            role = rng.choice([r for r in ROLES if r not in taken])  # autofilled
        taken.add(role)
        roles.append(role)
    return roles


def _pick_champion(
    rng: random.Random,
    role: Role,
    pool: Sequence[tuple[str, float]],
    picked: set[int],
    *,
    loyalty: float,
) -> int:
    options = [
        (CHAMPIONS_BY_KEY[key].id, weight)
        for key, weight in pool
        if CHAMPIONS_BY_KEY[key].id not in picked
    ]
    if options and rng.random() < loyalty:
        return _weighted_choice(rng, options)
    fallback = [c.id for c in CHAMPIONS_BY_ROLE[role] if c.id not in picked]
    return rng.choice(fallback)


def _level_at(current: int, now: datetime, at: datetime, days_per_level: float) -> int:
    days = max(0.0, (now - at).total_seconds() / 86400)
    return max(30, current - int(days / days_per_level))


def _opponent_candidates(
    states: Sequence[_OpponentState], start: datetime, lobby: float, used: set[str]
) -> list[_OpponentState]:
    for window in (250, 400, 600, 900, 1400, 10_000):
        found = [
            s
            for s in states
            if s.puuid not in used
            and s.free_at <= start
            and abs(s.opponent.rank_value - lobby) <= window
        ]
        if len(found) >= 12:
            return found
    return [s for s in states if s.puuid not in used]


def _ladder_for(m: _Member, flex: bool) -> tuple[str, _Ladder]:
    """(queue_type, ladder) a game in this queue counts towards for ``m``."""
    if flex and m.flex is not None:
        return RANKED_FLEX_SR, m.flex
    return RANKED_SOLO_5x5, m.solo


def _tracked_slots(
    rng: random.Random,
    group: Sequence[_Member],
    team: int,
    taken_roles: set[Role],
    picked: set[int],
    now: datetime,
    start: datetime,
) -> list[Slot]:
    roles = _assign_roles(rng, [m.player for m in group], taken_roles)
    slots: list[Slot] = []
    for m, role in zip(group, roles, strict=True):
        p = m.player
        champ = _pick_champion(rng, role, p.pool_for(role), picked, loyalty=0.9)
        picked.add(champ)
        slots.append(
            Slot(
                puuid=m.puuid,
                game_name=p.game_name,
                tag_line=p.tag_line,
                profile_icon_id=p.profile_icon_id,
                summoner_level=_level_at(p.summoner_level, now, start, 5.0),
                team_id=team,
                role=role,
                champion_id=champ,
                skill=p.skill,
                aggression=p.aggression,
                vision=p.vision,
                pings=p.pings,
                flash_on_d=p.flash_on_d,
            )
        )
    return slots


def _opponent_slots(
    rng: random.Random,
    states: Sequence[_OpponentState],
    game: _Game,
    lobby: float,
    roles_taken: dict[int, set[Role]],
    used: set[str],
    picked: set[int],
    now: datetime,
) -> list[Slot]:
    """Fill every open role on both teams with strangers close to the lobby's rank."""
    candidates = _opponent_candidates(states, game.start, lobby, used)
    slots: list[Slot] = []
    for team in (BLUE, RED):
        for role in ROLES:
            if role in roles_taken[team]:
                continue
            pool = [s for s in candidates if s.puuid not in used] or [
                s for s in states if s.puuid not in used
            ]
            preferred = [s for s in pool if s.opponent.main_role == role]
            chosen = rng.choice(preferred) if preferred and rng.random() < 0.8 else rng.choice(pool)
            used.add(chosen.puuid)
            o = chosen.opponent
            favorites = tuple((key, 1.0) for key in o.favorites) if o.main_role == role else ()
            champ = _pick_champion(rng, role, favorites, picked, loyalty=0.55)
            picked.add(champ)
            slots.append(
                Slot(
                    puuid=chosen.puuid,
                    game_name=o.game_name,
                    tag_line=o.tag_line,
                    profile_icon_id=o.profile_icon_id,
                    summoner_level=_level_at(o.summoner_level, now, game.start, 7.0),
                    team_id=team,
                    role=role,
                    champion_id=champ,
                    skill=o.skill,
                    aggression=o.aggression,
                    vision=o.vision,
                    pings=o.pings,
                    flash_on_d=o.flash_on_d,
                )
            )
            chosen.free_at = game.end + timedelta(minutes=5)
            chosen.appearances += 1
            chosen.last_end = game.end
    return slots


def build_dataset(
    *,
    players: int = 8,
    matches: int = 220,
    seed: int = 7,
    now: datetime | None = None,
    platform: str = "na1",
    reserved: Collection[tuple[str, str]] = (),
) -> DemoDataset:
    """Generate the full demo dataset in memory (no I/O). Same arguments, same data.

    ``reserved`` holds :func:`hextrack.riotid.riot_id_key` tuples of real accounts the demo
    must not impersonate: opponents avoid them and roster members get a ``DEMO`` tag.
    """
    if players < 1:
        raise ValueError("players must be at least 1")
    if matches < 1:
        raise ValueError("matches must be at least 1")
    validate_roster()
    now = (now or datetime.now(UTC)).astimezone(UTC).replace(microsecond=0)
    rng = random.Random(seed)
    taken_names: set[tuple[str, str]] = set(reserved)
    roster = _build_roster(rng, players, taken_names)

    members: list[_Member] = []
    for i, player in enumerate(roster):
        solo, flex = _initial_ladders(rng, player)
        members.append(_Member(i, player, player.puuid, solo, flex))

    values = [m.solo.value for m in members]
    n_opponents = max(60, min(2000, round(matches * 15 / 11)))
    opponents = make_opponents(
        rng,
        n_opponents,
        rank_range=(max(0, min(values) - 350), max(values) + 450),
        taken=taken_names,
    )
    anchor = schedule_anchor(now)
    window_start = anchor - timedelta(days=WINDOW_DAYS, hours=SESSION_DAY_END_HOUR)
    opp_states = [
        _OpponentState(o, o.puuid, free_at=window_start - timedelta(days=1)) for o in opponents
    ]
    games = _schedule(rng, members, matches, anchor)
    form: dict[str, deque[int]] = {m.puuid: deque(maxlen=FORM_GAMES) for m in members}

    tracked_since = {
        m.index: window_start - timedelta(days=rng.uniform(1.0, 3.0), minutes=rng.randint(0, 600))
        for m in members
    }
    snapshots: dict[tuple[str, str], list[DemoSnapshot]] = {}
    for m in members:
        snapshots[(m.puuid, RANKED_SOLO_5x5)] = [
            m.solo.snapshot(m.puuid, RANKED_SOLO_5x5, tracked_since[m.index], False)
        ]
        if m.flex is not None:
            snapshots[(m.puuid, RANKED_FLEX_SR)] = [
                m.flex.snapshot(m.puuid, RANKED_FLEX_SR, tracked_since[m.index], False)
            ]

    payloads: list[dict[str, Any]] = []
    for number, game in enumerate(games, start=1):
        match_rng = random.Random(rng.getrandbits(64))
        is_flex = game.queue_id == FLEX_QUEUE
        allies = [members[i] for i in game.allies]
        rivals = [members[i] for i in game.rivals]
        in_game = allies + rivals
        lobby = sum(_ladder_for(m, is_flex)[1].value for m in in_game) / len(in_game)
        roster_side = BLUE if match_rng.random() < 0.5 else RED
        other_side = RED if roster_side == BLUE else BLUE

        picked: set[int] = set()
        used: set[str] = {m.puuid for m in in_game}
        roles_taken: dict[int, set[Role]] = {roster_side: set(), other_side: set()}
        slots = _tracked_slots(
            match_rng, allies, roster_side, roles_taken[roster_side], picked, now, game.start
        )
        slots += _tracked_slots(
            match_rng, rivals, other_side, roles_taken[other_side], picked, now, game.start
        )
        slots += _opponent_slots(match_rng, opp_states, game, lobby, roles_taken, used, picked, now)

        tracked_puuids = {m.puuid for m in in_game}
        edge = 0.0
        for slot in slots:
            sign = 1 if slot.team_id == BLUE else -1
            if slot.puuid in tracked_puuids:
                edge += sign * TRACKED_SKILL_WEIGHT * slot.skill
                edge -= sign * FORM_WEIGHT * sum(form[slot.puuid])
            else:
                edge += sign * OPPONENT_SKILL_WEIGHT * slot.skill
        p_blue = min(0.75, max(0.25, 0.5 + edge))
        winner = BLUE if match_rng.random() < p_blue else RED

        plan = MatchPlan(
            match_id=f"{DEMO_MATCH_PREFIX}{number}",
            game_id=number,
            queue_id=game.queue_id,
            start=game.start,
            duration_s=game.duration_s,
            winning_team=winner,
            remake=game.remake,
            slots=tuple(slots),
            lobby_elo=min(1.0, max(0.0, lobby / MASTER_BASE)),
            platform_id=platform.upper(),
        )
        payloads.append(generate_match(plan, match_rng))

        if game.remake:
            continue
        taken_at = game.end + timedelta(minutes=match_rng.uniform(1.0, 4.0))
        for m in in_game:
            queue_type, lad = _ladder_for(m, is_flex)
            team = roster_side if m in allies else other_side
            skill = m.player.skill
            gain = round(min(30, max(12, 21 + 6 * skill + match_rng.gauss(0.0, 1.5))))
            loss = round(min(28, max(10, 19 - 5 * skill + match_rng.gauss(0.0, 1.5))))
            lad.apply(team == winner, gain, loss)
            form[m.puuid].append(1 if team == winner else -1)
            snapshots[(m.puuid, queue_type)].append(
                lad.snapshot(m.puuid, queue_type, taken_at, False)
            )

    # Separate streams for what depends on the exact time of day (heartbeats run until now),
    # so the games and the people stay identical.
    hb_rng = random.Random(rng.getrandbits(64))
    rng = random.Random(rng.getrandbits(64))
    # Heartbeats: the poller re-records an unchanged standing after 24h (a little later when
    # the worker was down), until now.
    all_snapshots: list[DemoSnapshot] = []
    for series in snapshots.values():
        series.sort(key=lambda s: s.taken_at)
        filled: list[DemoSnapshot] = []
        for i, snap in enumerate(series):
            filled.append(snap)
            limit = series[i + 1].taken_at if i + 1 < len(series) else now
            last = snap
            while True:
                at = last.taken_at + timedelta(hours=24 + hb_rng.uniform(0.0, 16.0))
                if at >= limit or at >= now:
                    break
                last = DemoSnapshot(
                    puuid=snap.puuid,
                    queue_type=snap.queue_type,
                    tier=snap.tier,
                    rank=snap.rank,
                    lp=snap.lp,
                    wins=snap.wins,
                    losses=snap.losses,
                    rank_value=snap.rank_value,
                    taken_at=at,
                    is_heartbeat=True,
                )
                filled.append(last)
        all_snapshots.extend(filled)

    summoners: list[DemoSummoner] = []
    for m in members:
        p = m.player
        since = tracked_since[m.index]
        summoners.append(
            DemoSummoner(
                puuid=m.puuid,
                game_name=p.game_name,
                tag_line=p.tag_line,
                profile_icon_id=p.profile_icon_id,
                summoner_level=p.summoner_level,
                is_tracked=True,
                tracked_since=since,
                last_refreshed_at=now - timedelta(minutes=rng.uniform(1.0, 20.0)),
                backfilled_at=since + timedelta(minutes=3),
            )
        )
    for state in opp_states:
        if state.appearances == 0 or state.last_end is None:
            continue
        o = state.opponent
        looked_up = min(now, state.last_end + timedelta(minutes=rng.uniform(10.0, 180.0)))
        summoners.append(
            DemoSummoner(
                puuid=state.puuid,
                game_name=o.game_name,
                tag_line=o.tag_line,
                profile_icon_id=o.profile_icon_id,
                summoner_level=o.summoner_level,
                is_tracked=False,
                tracked_since=None,
                last_refreshed_at=looked_up,
                backfilled_at=None,
            )
        )
        tier, rank, lp = standing_for_value(o.rank_value)
        total = rng.randint(40, 400)
        wins = round(total * rng.uniform(0.45, 0.56))
        all_snapshots.append(
            DemoSnapshot(
                puuid=state.puuid,
                queue_type=RANKED_SOLO_5x5,
                tier=tier,
                rank=rank,
                lp=lp,
                wins=wins,
                losses=total - wins,
                rank_value=rank_value(tier, rank, lp),
                taken_at=looked_up,
                is_heartbeat=False,
            )
        )

    all_snapshots.sort(key=lambda s: (s.taken_at, s.puuid, s.queue_type))
    return DemoDataset(now=now, summoners=summoners, matches=payloads, snapshots=all_snapshots)


# --- database --------------------------------------------------------------------------------


def _is_demo_match(column: Any) -> Any:
    return column.startswith(DEMO_MATCH_PREFIX, autoescape=True)


def _is_demo_puuid(column: Any) -> Any:
    return column.startswith(DEMO_PUUID_PREFIX, autoescape=True)


async def delete_demo_data(session: AsyncSession) -> int:
    """Delete every ``DEMO_`` match (with its participants), every ``demo-`` summoner (with
    its rank snapshots) and bot events that refer to either. Returns the number of matches
    deleted. Real data is never touched. Does not commit."""
    await session.execute(
        delete(BotEvent).where(
            or_(
                _is_demo_puuid(BotEvent.payload["puuid"].astext),
                _is_demo_match(BotEvent.payload["match_id"].astext),
            )
        )
    )
    await session.execute(delete(MatchParticipant).where(_is_demo_match(MatchParticipant.match_id)))
    result = await session.execute(
        delete(Match).where(_is_demo_match(Match.match_id)).returning(Match.match_id)
    )
    deleted = len(result.all())
    await session.execute(delete(RankSnapshot).where(_is_demo_puuid(RankSnapshot.puuid)))
    await session.execute(delete(Summoner).where(_is_demo_puuid(Summoner.puuid)))
    return deleted


async def clear_demo(settings: Settings) -> int:
    """Delete all demo data (see :func:`delete_demo_data`) without seeding anything new, e.g.
    once real games have been imported. Returns the number of demo matches deleted."""
    engine = make_async_engine(settings, pool_size=1, max_overflow=0)
    try:
        async with make_session_factory(engine)() as session:
            deleted = await delete_demo_data(session)
            await session.commit()
    finally:
        await engine.dispose()
    logger.info("deleted %d demo matches and all demo summoners", deleted)
    return deleted


def _load_scorer(model_dir: Path) -> Scorer | None:
    """The active AI model, or None (demo data is then stored unscored)."""
    from hextrack.hextrack_ai.inference import Scorer

    try:
        scorer = Scorer.load(model_dir)
    except Exception:
        logger.exception("could not load the AI model from %s; seeding without scores", model_dir)
        return None
    if scorer is None:
        logger.info("no AI model in %s; demo matches are stored unscored", model_dir)
    return scorer


async def _insert_summoners(session: AsyncSession, dataset: DemoDataset, platform: str) -> set[str]:
    """Insert missing demo summoners; returns the demo puuids present afterwards."""
    rows = [
        {
            "puuid": s.puuid,
            "game_name": s.game_name,
            "tag_line": s.tag_line,
            "platform": platform,
            "profile_icon_id": s.profile_icon_id,
            "summoner_level": s.summoner_level,
            "is_tracked": s.is_tracked,
            "tracked_since": s.tracked_since,
            "last_refreshed_at": s.last_refreshed_at,
            "backfilled_at": s.backfilled_at,
        }
        for s in dataset.summoners
    ]
    for chunk_start in range(0, len(rows), 500):
        chunk = rows[chunk_start : chunk_start + 500]
        # No conflict target: skips both an existing puuid and a Riot ID already used by a
        # real account.
        await session.execute(insert(Summoner).values(chunk).on_conflict_do_nothing())
    wanted = [s.puuid for s in dataset.summoners]
    present = set(
        (await session.scalars(select(Summoner.puuid).where(Summoner.puuid.in_(wanted)))).all()
    )
    missing = len(wanted) - len(present)
    if missing:
        logger.warning("%d demo summoners clash with existing Riot IDs and were skipped", missing)
    return present


async def _insert_snapshots(session: AsyncSession, dataset: DemoDataset, present: set[str]) -> int:
    """Insert rank history for demo summoners that have none yet (keeps reruns idempotent)."""
    have_history = set(
        (
            await session.scalars(
                select(RankSnapshot.puuid)
                .where(_is_demo_puuid(RankSnapshot.puuid))
                .group_by(RankSnapshot.puuid)
            )
        ).all()
    )
    rows = [
        {
            "puuid": s.puuid,
            "queue_type": s.queue_type,
            "tier": s.tier,
            "rank": s.rank,
            "lp": s.lp,
            "wins": s.wins,
            "losses": s.losses,
            "rank_value": s.rank_value,
            "taken_at": s.taken_at,
            "is_heartbeat": s.is_heartbeat,
        }
        for s in dataset.snapshots
        if s.puuid in present and s.puuid not in have_history
    ]
    for chunk_start in range(0, len(rows), 1000):
        await session.execute(insert(RankSnapshot).values(rows[chunk_start : chunk_start + 1000]))
    return len(rows)


async def _real_riot_ids(
    session: AsyncSession, dataset: DemoDataset, platform: str
) -> set[tuple[str, str]]:
    """Riot IDs in ``dataset`` that already belong to non-demo summoners on ``platform``."""
    wanted = {(s.game_name.lower(), s.tag_line.lower()) for s in dataset.summoners}
    found: set[tuple[str, str]] = set()
    pairs = sorted(wanted)
    for start in range(0, len(pairs), 500):
        chunk = pairs[start : start + 500]
        rows = await session.execute(
            select(Summoner.game_name, Summoner.tag_line).where(
                tuple_(func.lower(Summoner.game_name), func.lower(Summoner.tag_line)).in_(chunk),
                Summoner.platform == platform,
                ~_is_demo_puuid(Summoner.puuid),
            )
        )
        found.update(riot_id_key(name, tag) for name, tag in rows.all())
    return found


async def _dataset_avoiding_real_accounts(
    session: AsyncSession,
    *,
    players: int,
    matches: int,
    seed: int,
    now: datetime | None,
    platform: str,
) -> DemoDataset:
    """:func:`build_dataset`, regenerated with clashing Riot IDs reserved until no demo
    summoner shares a Riot ID with a real account."""
    reserved: set[tuple[str, str]] = set()
    for _attempt in range(5):
        dataset = build_dataset(
            players=players,
            matches=matches,
            seed=seed,
            now=now,
            platform=platform,
            reserved=reserved,
        )
        clashes = await _real_riot_ids(session, dataset, platform) - reserved
        if not clashes:
            return dataset
        logger.info("%d demo Riot IDs belong to real accounts; regenerating", len(clashes))
        reserved |= clashes
    return dataset


async def seed_demo(
    settings: Settings,
    *,
    reset: bool,
    players: int = 8,
    matches: int = 220,
    seed: int = 7,
    now: datetime | None = None,
) -> SeedReport:
    """Create ``players`` tracked summoners (plus the opponents they meet), ``matches``
    synthetic ranked games (10 participants each, generated from ``random.Random(seed)``) and
    their rank history, all through the real ingestion path. Games are scored when an AI
    model is available in ``settings.model_dir``.

    With ``reset``, existing demo data (``DEMO_`` matches, ``demo-`` summoners, their rank
    snapshots and bot events) is deleted first; real data is never touched. Without it the
    call is idempotent: existing demo matches and rank histories are left as they are.
    Demo Riot IDs never collide with stored real accounts: clashing opponents are renamed
    and a clashing roster member gets a ``DEMO`` tag. ``now`` pins the clock (tests); games
    end before the latest 05:00 UTC, so a seed gives the same games at any time of day.
    """
    engine = make_async_engine(settings, pool_size=2, max_overflow=0)
    try:
        factory = make_session_factory(engine)
        async with factory() as session:
            dataset = await _dataset_avoiding_real_accounts(
                session,
                players=players,
                matches=matches,
                seed=seed,
                now=now,
                platform=settings.riot_platform,
            )
        scorer = _load_scorer(settings.model_dir)
        # Offline client: nothing here talks to Riot, and a stray call fails fast.
        async with RiotClient(settings.model_copy(update={"riot_api_key": None})) as riot:
            ctx = IngestContext(
                settings=settings, session_factory=factory, riot=riot, scorer=scorer
            )
            async with factory() as session:
                deleted = 0
                if reset:
                    deleted = await delete_demo_data(session)
                    await session.commit()
                    logger.info("deleted %d demo matches and all demo summoners", deleted)

                present = await _insert_summoners(session, dataset, settings.riot_platform)
                await session.commit()

                created = participants = scored = 0
                for i, raw in enumerate(dataset.matches, start=1):
                    result = await ingest_match_json(ctx, session, raw, enqueue_events=False)
                    if result.created:
                        created += 1
                        participants += result.participants
                        scored += 1 if result.scored else 0
                    if i % COMMIT_EVERY == 0:
                        await session.commit()
                await session.commit()

                snapshots = await _insert_snapshots(session, dataset, present)
                await session.commit()
    finally:
        await engine.dispose()

    tracked = sum(1 for s in dataset.summoners if s.is_tracked and s.puuid in present)
    report = SeedReport(
        players=tracked,
        matches=created,
        participants=participants,
        rank_snapshots=snapshots,
        reset=reset,
        opponents=len(present) - tracked,
        scored_matches=scored,
        deleted_matches=deleted,
    )
    logger.info(
        "demo seed: %d tracked players, %d opponents, %d new matches (%d scored), "
        "%d rank snapshots",
        report.players,
        report.opponents,
        report.matches,
        report.scored_matches,
        report.rank_snapshots,
    )
    return report
